name: Continuous Integration

on:
  push:
  pull_request:
    types: [labeled, opened, synchronize]

jobs:
    link_check:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.9'
        - name: Broken Link Script
          run: |
            chmod +x ./.github/workflow_scripts/link_check.sh && ./.github/workflow_scripts/link_check.sh
        - name: git
          run: |
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"
            git fetch https://github.com/shreyash2106/autogluon-webchecker
            git add *.csv -f
            git commit -m "csv files with broken links"
            git push
        - name: Check CSV Files
          shell: python
          run: |
            import pandas as pd
            df = pd.read_csv("Broken Links Stable.csv") 
            if not df.empty: 
                exit(1)
            df = pd.read_csv("Broken Links Dev.csv") 
            if not df.empty: 
                exit(1)
