name: Continuous Integration

on:
  push:
  pull_request:
    types: [labeled, opened, synchronize]

jobs:
    link_check:
        runs-on: ubuntu-latest
        steps:
        - name: Broken Link Checker Action
          uses: technote-space/broken-link-checker-action@v1.1.3
          with:
            TARGET: https://auto.gluon.ai/stable/index.html
            RECURSIVE: true
